# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
    - package-ecosystem: github-actions
      directory: "/"
      schedule:
          interval: daily
          time: "03:00"

    - package-ecosystem: gomod
      directory: "/"
      schedule:
          interval: daily
          time: "03:05"
      groups:
          cosmos-sdk-dependencies:
              patterns:
                  - "github.com/cosmos/*"
                  - "github.com/cometbft/cometbft"
              update-types:
                  - "patch"
      labels:
          - "A:automerge"
          - dependencies
