# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
    - package-ecosystem: github-actions
      directory: "/"
      schedule:
          interval: daily
          time: "03:00"
      assignees:
          - "RogerKSI"
          - "taobun"

    - package-ecosystem: gomod
      directory: "/"
      schedule:
          interval: daily
          time: "03:05"
      ignore:
          - dependency-name: "cosmossdk.io/*"
            update-types: ["version-update:semver-major"]
          - dependency-name: "github.com/cosmos/cosmos-sdk"
            update-types: ["version-update:semver-major"]
          - dependency-name: "github.com/cometbft/*"
            update-types: ["version-update:semver-major"]
      assignees:
          - "RogerKSI"
          - "taobun"
