linters-settings:

linters:
  disable-all: true
  enable:
    - bodyclose
    - depguard
    - gofmt
    - goimports
    - misspell
    - typecheck
    - whitespace
    - ireturn

run:
  timeout: 5m
  go: '1.18'
